#let input = (
  CHARACTERNAME                             : "",
  BACKGROUND                                : "",
  CLASS                                     : "",
  SPECIES                                   : "",
  SUBCLASS                                  : "",

  LEVEL                                     : "",
  XP                                        : "",

  AC                                        : "",
  SHIELD                                    : false,

  TEMPORARY                                 : "",
  SPENT                                     : "",
  MAX_HITPOINTS                             : "",
  MAX_HITDICE                               : "",
  CURRENT                                   : "",
  SUCCESSES                                 : 0,
  FAILURES                                  : 0,

  PROFICIENCYBONUS                          : "",

  STRENGTH_SCORE                            : "",
  STRENGTH_MODIFIER                         : "",
  STRENGTH_SAVE                             : "",
  STRENGTH_PROFICIENCY                      : false,
  ATHLETICS_MODIFIER                        : "",
  ATHLETICS_PROFICIENCY                     : false,
  
  DEXTERITY_SCORE                           : "",
  DEXTERITY_MODIFIER                        : "",
  DEXTERITY_SAVE                            : "",
  DEXTERITY_PROFICIENCY                     : false,
  ACROBATICS_MODIFIER                       : "", 
  ACROBATICS_PROFICIENCY                    : false,
  SLEIGHTOFHAND_MODIFIER                    : "", 
  SLEIGHTOFHAND_PROFICIENCY                 : false,
  STEALTH_MODIFIER                          : "",
  STEALTH_PROFICIENCY                       : false,
  
  CONSTITUTION_SCORE                        : "",
  CONSTITUTION_MODIFIER                     : "",
  CONSTITUTION_SAVE                         : "",
  CONSTITITION_PROFICIENCY                  : false,
  
  INTELLIGENCE_SCORE                        : "",
  INTELLIGENCE_MODIFIER                     : "",
  INTELLIGENCE_SAVE                         : "",
  INTELLIGENCE_PROFICIENCY                  : false,
  ARCANA_MODIFIER                           : "", 
  ARCANA_PROFICIENCY                        : false,
  HISTORY_MODIFIER                          : "", 
  HISTORY_PROFICIENCY                       : false,
  INVESTIGATION_MODIFIER                    : "", 
  INVESTIGATION_PROFICIENCY                 : false,
  NATURE_MODIFIER                           : "", 
  NATURE_PROFICIENCY                        : false,
  RELIGION_MODIFIER                         : "",
  RELIGION_PROFICIENCY                      : false,
  
  WISDOM_SCORE                              : "", 
  WISDOM_MODIFIER                           : "", 
  WISDOM_SAVE                               : "", 
  WISDOM_PROFICIENCY                        : false,
  ANIMALHANDLING_MODIFIER                   : "", 
  ANIMALHANDLING_PROFICIENCY                : false,
  INSIGHT_MODIFIER                          : "", 
  INSIGHT_PROFICIENCY                       : false,
  MEDICINE_MODIFIER                         : "", 
  MEDICINE_PROFICIENCY                      : false,
  PERCEPTION_MODIFIER                       : "", 
  PERCEPTION_PROFICIENCY                    : false,
  SURVIVAL_MODIFIER                         : "",
  SURVIVAL_PROFICIENCY                      : false,
  
  CHARISMA_SCORE                            : "", 
  CHARISMA_MODIFIER                         : "", 
  CHARISMA_SAVE                             : "", 
  CHARISMA_PROFICIENCY                      : false,
  DECEPTION_MODIFIER                        : "", 
  DECEPTION_PROFICIENCY                     : false,
  INTIMIDATION_MODIFIER                     : "", 
  INTIMIDATION_PROFICIENCY                  : false,
  PERFORMANCE_MODIFIER                      : "", 
  PERFORMANCE_PROFICIENCY                   : false,
  PERSUASION_MODIFIER                       : "",
  PERSUASION_PROFICIENCY                    : false,

  HEROICINSPIRATION                         : false,

  ARMOR_LIGHT                               : false,
  ARMOR_HEAVY                               : false,
  ARMOR_MEDIUM                              : false,
  SHIELDS                                   : false,

  WEAPONS                                   : "",
  TOOLS                                     : "",

  INITIATIVE                                : "",
  SPEED                                     : "",
  SIZE                                      : "",
  PASSIVEPERCEPTION                         : "",

  ATTACKSLIST                              : (
                                                // ("Name", "Damage", "Notes"),
                                             ),

  CLASSFEATURES1                            : "",
  CLASSFEATURES2                            : "",
  
  SPECIESTRAITS                             : "",
  
  FEATS                                     : "",

  SPELLCASTINGABILITY                       : "",
  SPELLCASTINGMODIFIER                      : "",
  SPELLSAVEDC                               : "",
  SPELLATTACKBONUS                          : "",

  SPELLSLOTS_LEVEL1                         : "",
  SPELLSLOTS_LEVEL1_EXPENDED                : 0,
  SPELLSLOTS_LEVEL2                         : "",
  SPELLSLOTS_LEVEL2_EXPENDED                : 0,
  SPELLSLOTS_LEVEL3                         : "",
  SPELLSLOTS_LEVEL3_EXPENDED                : 0,
  SPELLSLOTS_LEVEL4                         : "",
  SPELLSLOTS_LEVEL4_EXPENDED                : 0,
  SPELLSLOTS_LEVEL5                         : "",
  SPELLSLOTS_LEVEL5_EXPENDED                : 0,
  SPELLSLOTS_LEVEL6                         : "",
  SPELLSLOTS_LEVEL6_EXPENDED                : 0,
  SPELLSLOTS_LEVEL7                         : "",
  SPELLSLOTS_LEVEL7_EXPENDED                : 0,
  SPELLSLOTS_LEVEL8                         : "",
  SPELLSLOTS_LEVEL8_EXPENDED                : 0,
  SPELLSLOTS_LEVEL9                         : "",
  SPELLSLOTS_LEVEL9_EXPENDED                : 0,

  SPELLLIST                                 : (
                                                  // ("Level", "Name", "Time", "Range", false, false, false, "Notes"),
                                              ),
  
  APPEARANCE                                : "",
  BACKSTORY_PERSONALITY                     : "",
  ALIGNMENT                                 : "",
  LANGUAGES                                 : "",
  EQUIPMENT                                 : "",
  ATUNED_MAGICITEM1                         : "",
  ATUNED_MAGICITEM2                         : "",
  ATUNED_MAGICITEM3                         : "",

  COPPER                                    : "",
  SILVER                                    : "",
  ELECTRUM                                  : "",
  GOLD                                      : "",
  PLATINUM                                  : "",
)